### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by erinyoung** [boasvdp/assembly_snptyper#5]
Hi! I really like using assembly_snptyper and would like to make a container with it. 

Can you include a LICENSE in this repo?

This helps me prove to others that I'm not using your wonderful tool inappropriately.

**Comment by boasvdp** [comment]
Thanks, appreciate the kind words! I have add an MIT license in release 0.1.1

**Comment by erinyoung** [comment]
Thank you!
